# Generated by Django 2.1.1 on 2018-09-12 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='竞赛名称')),
                ('sponser', models.CharField(max_length=100, verbose_name='主办方')),
                ('startdate', models.DateField(auto_now_add=True, verbose_name='创办时间')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuehao', models.CharField(max_length=12, verbose_name='学号')),
                ('student', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('attachment', models.CharField(blank=True, max_length=200, null=True)),
                ('shenhe', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Competition', verbose_name='竞赛名称')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='获奖等级')),
            ],
        ),
        migrations.CreateModel(
            name='Sclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='年级')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Sclass', verbose_name='年级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学号')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Grade', verbose_name='获奖情况'),
        ),
    ]
