# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180816_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=100, verbose_name='竞赛名称'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='sponser',
            field=models.CharField(max_length=100, verbose_name='主办方'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='startdate',
            field=models.DateField(auto_now_add=True, verbose_name='创办时间'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Competition', verbose_name='竞赛名称'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Grade', verbose_name='获奖情况'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='student',
            field=models.CharField(max_length=50, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50, verbose_name='获奖等级'),
        ),
        migrations.AlterField(
            model_name='sclass',
            name='name',
            field=models.CharField(max_length=30, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Sclass', verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学号'),
        ),
    ]
