# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180816_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='shenhe',
            field=models.BooleanField(default=False),
        ),
    ]
