# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_entry_shenhe'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='xuehao',
            field=models.CharField(default='916107820236', max_length=12, verbose_name='学号'),
        ),
    ]
