# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_entry_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
