# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_entry_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
