# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_entry_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='attachment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
